### ISSUE TITLE
Suggestions for new operation: countDistinct

### ISSUE THREAD

**Issue by malcook** [arq5x/filo#6]
countDistinct would tabulate the number of distinct values appear in opCol

**Comment by arq5x** [comment]
Hi Malcom,

Indeed! I have added this to my local bedtools repository (I moved groupby back into bedtools as of v2.15.0, but confusingly haven't removed/updated this repo - sorry).  I am in the middle of some other changes, so I haven't pushed those changes to the public repo, but hope to very soon.

**Comment by arq5x** [comment]
Hi Malcolm,

I just updated the bedtools repository with a version of groupBy that includes "distinct" and "count_distinct" options.
